### ISSUE TITLE
Releaser Configuration

### ISSUE THREAD

**Issue by kylef** [kylef/maintain#10]
It should be possible for a user to specify configuration options for a releaser, both in a config file and in the command line interface.

This allows features such as #5.

```yaml
releasers:
  git:
    tag_format: v{version}
    commit_format: Release {version}
```

```
--releaser-config 'git:tag_format: v{version}'
```
