### ISSUE TITLE
Support publishing artefacts to GitHub releaser

### ISSUE THREAD

**Issue by kylef** [kylef/maintain#11]
After #10, there could be artefacts list in config:

```yaml
releasers:
  github:
    artefacts:
      - drafter.js.min
```
